-- CREATE TABLE USERS(USER_ID bigint, USERNAME varchar(30), NAME varchar(50), EMAIL VARCHAR(50), DOB timestamp, GENDER varchar(1), BIO VARCHAR(500), CREATED_ON TIMESTAMP, PHOTO BLOB);
-- CREATE TABLE FOLLOWS(USER_ID bigint, FOLLOWER_ID bigint);
-- CREATE TABLE LIKES(USER_ID bigint, POST_ID bigint);
-- CREATE TABLE POSTS(POST_ID bigint, FROM_USER_ID bigint, TO_USER_ID BIGINT, MESSAGE VARCHAR(500), POSTED_ON TIMESTAMP, IS_ANON BOOL, IS_COMMENT BOOL, COMMENT_ON BIGINT);
-- CREATE TABLE AUTH(USER_ID bigint, PASSWORD varchar(145));
-- CREATE TABLE SESSIONS(USER_ID BIGINT, COOKIE VARCHAR(36));

SELECT * FROM USERS ORDER BY USER_ID DESC;
SELECT * FROM FOLLOWS;
SELECT * FROM LIKES;
SELECT * FROM POSTS;
SELECT * FROM AUTH ORDER BY USER_ID DESC;

SELECT U.USER_ID, U.USERNAME, U.EMAIL, A.PASSWORD FROM USERS U JOIN AUTH A ON U.USER_ID = A.USER_ID;